/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fm_aiyinsitan_common_utils_AudioUtil */

#ifndef _Included_com_fm_aiyinsitan_common_utils_AudioUtil
#define _Included_com_fm_aiyinsitan_common_utils_AudioUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fm_aiyinsitan_common_utils_AudioUtil
 * Method:    ffmpegcore
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fm_aiyinsitan_common_utils_AudioUtil_ffmpegcore
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     com_fm_aiyinsitan_common_utils_AudioUtil
 * Method:    getRotation
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fm_aiyinsitan_common_utils_AudioUtil_getRotation
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fm_aiyinsitan_common_utils_AudioUtil
 * Method:    getAudioLoudness
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fm_aiyinsitan_common_utils_AudioUtil_getAudioLoudness
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
